name: Build Docs

on:
  push:
    branches: ['master', 'main']
  workflow_dispatch:

env:
  PYTHON_VERSION_DEFAULT: "3.10"

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions: {}

jobs:
  docs_json:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docgen
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}
          architecture: 'x64'

      - name: Generate Schema documentation
        run: ./gen.sh

      # Upload docs so the deploy job can pick them up
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docgen/docs  # The folder that has your generated docs

  deploy:
    runs-on: ubuntu-latest
    needs: docs_json
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        
      - name: Trigger Cloudflare Deploy Hook
        run: curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"
